services:
  nest-backend:
    container_name: realtime-leaderboard-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    env_file:
      - docker.env
    networks:
      - backend_network
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - docker.env
    networks:
      - postgres
      - backend_network
  pgadmin:
    networks:
      - postgres
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - docker.env
    ports:
      - '5050:80'
    depends_on:
      - postgres
networks:
  postgres:
    driver: bridge
  backend_network:
    driver: bridge
volumes:
  postgres_data: {}
